name: Helm Chart Tests
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "charts/k8s-mediaserver/**"
      - ".github/workflows/integration-tests.yml"
      - "test/kind/**"
  workflow_dispatch:

jobs:
  helm-linter:
    runs-on: ubuntu-24.04
    name: Run Helm linting
    steps:
      - uses: actions/checkout@v7

      - name: Setup helm
        uses: azure/setup-helm@v5
        with:
          version: "v3.13.0"
        id: install-helm

      - name: Add Helm repositories for dependencies
        run: |
          helm repo add k8s-mediaserver-charts https://95gabor.github.io/k8s-mediaserver-charts
          helm repo update

      - name: Update umbrella chart dependencies
        run: helm dependency update charts/k8s-mediaserver

      - name: Lint Helm template
        run: helm lint charts/k8s-mediaserver

      - name: Template Helm chart
        run: helm template charts/k8s-mediaserver

  helm-deploy-test:
    needs: helm-linter
    name: Deploy Helm chart to KinD cluster
    env:
      ingress_host: k8s-mediaserver.k8s.test
      plex_ingress_host: k8s-plex.k8s.test
      jellyfin_ingress_host: k8s-jelly.k8s.test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Setup helm
        uses: azure/setup-helm@v5
        with:
          version: "v3.13.0"

      - name: Add Helm repositories for dependencies
        run: |
          helm repo add k8s-mediaserver-charts https://95gabor.github.io/k8s-mediaserver-charts
          helm repo update

      - name: Update umbrella chart dependencies
        run: helm dependency update charts/k8s-mediaserver

      - name: Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind
          config: test/kind/kind-config.yaml

      - name: Deploy ingress to newly created cluster
        run: test/kind/setup-ingress.sh

      - name: Deploy Helm chart
        run: |
          helm upgrade --install k8s-mediaserver ./charts/k8s-mediaserver \
            -n mediaserver \
            --create-namespace \
            -f test/kind/helm-values.yaml
          test/kind/wait-for-pods.sh mediaserver

      - name: Test application endpoints
        run: test/kind/test-endpoints.sh
        env:
          INGRESS_HOST: ${{ env.ingress_host }}
          PLEX_INGRESS_HOST: ${{ env.plex_ingress_host }}
          JELLYFIN_INGRESS_HOST: ${{ env.jellyfin_ingress_host }}
